[package]
name = "teensy3"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>", "James Munns <james.munns@gmail.com"]
build = "build.rs"

# cargo:rerun-if-changed=target/thumbv7em-none-eabi/release/libteensy3.a
# cargo:rerun-if-changed=teensy3


[lib]
crate-type = ["staticlib"]
