[package]
name = "teensy3-sys"
version = "0.1.0"
authors = ["Paul Stoffregen <paul@pjrc.com>", "Simon Sapin <simon.sapin@exyr.org>", "James Munns <james.munns@gmail.com>"]
build = "build.rs"
license = "MIT/LGPL-2.1"

[lib]
path = "lib.rs"
